### ISSUE TITLE
Error during migration on Nextcloud 20

### ISSUE THREAD

**Issue by aszlig** [eblah/nextcloud-messagevault#1]
Hello,

I'm running automated tests on a range of Nextcloud versions on all apps published to the app store. Enabing `messagevault` fails to enable on Nextcloud 20 with the following exception:

```
Error: Class 'OCP\DB\Types' not found in .../apps/messagevault/lib/Migration/Version000000Date20211001000000.php:182
Stack trace:
#0 .../apps/messagevault/lib/Migration/Version000000Date20211001000000.php(23): OCA\MessageVault\Migration\Version000000Date20211001000000->createSmsAddress(Object(OC\DB\SchemaWrapper))
#1 .../lib/private/DB/MigrationService.php(483): OCA\MessageVault\Migration\Version000000Date20211001000000->changeSchema(Object(OC\Migration\SimpleOutput), Object(Closure), Array)
#2 .../lib/private/DB/MigrationService.php(419): OC\DB\MigrationService->executeStep('000000Date20211...', false)
#3 .../lib/private/Installer.php(157): OC\DB\MigrationService->migrate()
#4 .../core/Command/App/Enable.php(123): OC\Installer->installApp('messagevault', false)
#5 .../core/Command/App/Enable.php(93): OC\Core\Command\App\Enable->enableApp('messagevault', Array, false, Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 .../3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 .../3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 .../3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 .../3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 .../lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 .../console.php(85): OC\Console\Application->run()
#12 .../occ(11): require_once('...
#13 {main}
```

You can also view the [full log](https://headcounter.org/hydra/log/iaw6xnx5cy7p4vac6226imlf1iy8w0ga-vm-test-run-nextcloud-upgrade.drv) if you want.

Since according to your `README` you're in early stages of beta testing, I'd suggest to simply drop support for older Nextcloud versions, because at this stage I'd imagine that supporting them is just a maintenance burden. Since the app was broken on NC20 already when the app got published to the app store I'd say nobody will be mad at you :smiley:

**Comment by onfire4g05** [comment]
should be fixed in next release
